import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hello World from page.tsx',
  description: 'Generated by create next app',
}

export default function Home() {
  return (<></>)
}
