import Footer from '@/components/Footer/Footer'
import './globals.css'
import Header from '@/components/Head/Header'
import TopCategories from '@/components/Home/TopCategories'
import Articles from '@/components/Main/Articles'
import Newsletter from '@/components/Main/Newsletter'
import RelatedProducts from '@/components/Main/RelatedProducts'
import Slider from '@/components/Slider/Slider'
import { Inter } from 'next/font/google'
import Main from '@/components/Main/MainComponent'

export const metadata = {
  title: 'Hello World',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
})

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className + ' mb-16'}>
        <Header />
        <Main>
          {children}
        </Main>
        <Footer />
      </body>
    </html>
  )
}
