import { Inter } from 'next/font/google'
import Slider from "@/components/Slider/Slider";
import TopCategories from "@/components/Home/TopCategories";
import Newsletter from "@/components/Main/Newsletter";
import RelatedProducts from "@/components/Main/RelatedProducts";
import Articles from "@/components/Main/Articles";

export const metadata = {
    title: 'Hello World from page.tsx',
    description: 'Generated by create next app',
}



export default function Home() {
    return (<>
        <Slider />
        <TopCategories />
        <Newsletter />
        <RelatedProducts />
        <Articles />
    </>)
}
